"""empty message

Revision ID: 45e6d1b90681
Revises: 9e1835e7f1f4
Create Date: 2024-05-05 19:13:47.030335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e6d1b90681'
down_revision = '9e1835e7f1f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('quests_id', sa.Integer(), nullable=True),
    sa.Column('authenticated', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['quests_id'], ['quests.id'], ),
    sa.PrimaryKeyConstraint('username')
    )
    with op.batch_alter_table('quests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quests', schema=None) as batch_op:
        batch_op.drop_column('text')

    op.drop_table('users')
    # ### end Alembic commands ###
